apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 863298582437.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 863298582437.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: bf3489b0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
